POST http://localhost:3500/api/usuario
#Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzM4ZWNhODZjM2VlMTFhNWU2ODNhNWEiLCJjb3JyZW8iOiJyb2Npby5kb21pbmd1ZXpAYWRtaW4uY29tIiwiaWF0IjoxNjY0NjgyMzgxLCJleHAiOjE2NjQ2ODU5ODF9.aSkpx_uruMcCu-cIHo_w5d4qEJVTzHYSODQU7ZtRwyI
Content-Type: application/json

{
    "nombre": "Alba",
    "apellido": "Dominguez",
    "correo": "ita@correo.do",
    "clave": "ita123",
    "confirmaClave": "ita123"
}


###
GET http://localhost:3500/api/usuario
#Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzQ0YzM4MGIwMGZjMjFkNDM0MDIwYWMiLCJjb3JyZW8iOiJyb2Npby5kb21pbmd1ZXpAYWRtaW4uY29tIiwiaWF0IjoxNjY1NDUwODg1LCJleHAiOjE2NjU0NTQ0ODV9.MmroblBNClLiSIrGJNZPPqrrLZJp_I502MdlFUsbZy4

###
PUT http://localhost:3500/api/usuario/633f7db7cd22a5e2fc62093e
Content-Type: application/json

{
    "clave": "Pita"
}

###
DELETE http://localhost:3500/api/usuario/63378a1e49a8df6df58e9927

###
POST http://localhost:3500/api/usuario/login
Content-Type: application/json

{
    "correo" : "pita01@correo.do",
    "clave" : "Pita123"
}

###
PUT http://localhost:3500/api/usuario/changePassword/633f612898b4724701c1fe6f
Content-Type: application/json

{
    "oldPassword": "ita123",
    "newPassword": "Pita123"
}

###
GET http://localhost:3500/api/usuario/verify
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzNmN2RiN2NkMjJhNWUyZmM2MjA5M2UiLCJjb3JyZW8iOiJwaXRhMDFAY29ycmVvLmRvIiwiaWF0IjoxNjY1NDU5MDcyLCJleHAiOjE2NjU0NjI2NzJ9.pgrF-Xp-fXaX7p4OfE16btOEcx7MmOlF88wjFKW-M-I
